name: locorda_rdf_terms
description: A collection of well known RDF vocabularies as Dart constants, grouped in classes.
version: 0.11.0
resolution: workspace
homepage: https://locorda.dev/rdf-vocabularies/
repository: https://github.com/locorda/rdf-vocabularies
issue_tracker: https://github.com/locorda/rdf-vocabularies/issues
documentation: https://locorda.dev/rdf-vocabularies/
topics:
  - rdf
  - linked-data
  - semantic-web
readme: README.md
changelog: CHANGELOG.md
license: LICENSE
maintainers:
  - "Klas Kala√ü <habbatical@gmail.com>"

environment:
  sdk: ^3.7.0

dependencies:
  locorda_rdf_terms_core: ^0.11.0
  locorda_rdf_terms_common: ^0.11.0
  locorda_rdf_terms_schema: ^0.11.0
  locorda_rdf_terms_schema_http: ^0.11.0
  locorda_rdf_core: ^0.11.0

dev_dependencies:
  test: ^1.21.0
  lints: ">=5.1.1 <7.0.0"
  yaml: ^3.1.2
  path: ^1.8.0
